language: C

install:
  # Prerequisites
  -  "sudo apt-get install texinfo help2man cvs rcs autoconf autoconf-doc autoconf-archive automake texlive-base"

# try to build:
script: ./configure --enable-staticlib && make && make check && make distcheck

compiler:
  - clang
  - gcc

after_failure: aclocal --version && autoconf --version
