---

name: cooljeanius/stress-1.0.4
on:
  push:
    branches:
      - "**/*"
    tags:
      - "**/*"
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.6
      - run: sudo apt-get update
      - run: sudo apt-get install texinfo help2man cvs rcs autoconf autoconf-doc autoconf-archive automake texlive-base texlive-latex-base emacs-common-non-dfsg info ${{ matrix.compiler }}
      - run: "./configure --enable-staticlib CC=${{ matrix.compiler }} && make && make check"
      - run: "make distcheck"
        if: "${{ success() }}"
      - run: aclocal --version && autoconf --version
        if: "${{ failure() }}"
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: gzipped_tarfile-${{ matrix.compiler }}
          path: stress-1.0.4.tar.gz
    strategy:
      matrix:
        compiler:
          - clang
          - gcc
